import { createTheme } from "@mui/material/styles";
import { buildSaasComponents, buildTypography } from "./themeShared";

function createPresetTheme({
  mode,
  primary,
  backgroundDefault,
  surfaceBackground,
  surfaceBorder,
  surfaceShadow,
  paperShadow,
  appBarBackground,
  backdropBackground,
  tooltipBackground,
  tooltipArrow,
  textPrimary,
  textSecondary,
}) {
  return createTheme({
    palette: {
      mode,
      primary: { main: primary },
      background: {
        default: backgroundDefault,
        paper: surfaceBackground,
      },
      text: {
        primary: textPrimary,
        secondary: textSecondary,
      },
    },
    shape: { borderRadius: 18 },
    typography: buildTypography(),
    components: buildSaasComponents({
      mode,
      backgroundDefault,
      surfaceBackground,
      surfaceBorder,
      surfaceShadow,
      paperShadow,
      appBarBackground,
      backdropBackground,
      tooltipBackground,
      tooltipArrow,
      textPrimary,
      textSecondary,
    }),
  });
}

export const THEME_PRESETS = [
  {
    id: "dark_glass",
    name: "Dark Glass (Default)",
    theme: createPresetTheme({
      mode: "dark",
      primary: "#38bdf8",
      backgroundDefault: "#060b16",
      surfaceBackground: "rgba(10, 17, 32, 0.82)",
      surfaceBorder: "rgba(148, 163, 184, 0.16)",
      surfaceShadow: "0 24px 70px rgba(2, 6, 23, 0.34)",
      paperShadow: "0 24px 70px rgba(2, 6, 23, 0.34)",
      appBarBackground: "rgba(7, 16, 31, 0.78)",
      backdropBackground: "rgba(2, 6, 23, 0.72)",
      tooltipBackground: "#0f172a",
      tooltipArrow: "#0f172a",
      textPrimary: "#e5eefc",
      textSecondary: "#9aa8bf",
    }),
  },
  {
    id: "dark_solid",
    name: "Dark Solid",
    theme: createPresetTheme({
      mode: "dark",
      primary: "#22c55e",
      backgroundDefault: "#070b14",
      surfaceBackground: "#0f172a",
      surfaceBorder: "rgba(148, 163, 184, 0.16)",
      surfaceShadow: "0 24px 70px rgba(2, 6, 23, 0.36)",
      paperShadow: "0 24px 70px rgba(2, 6, 23, 0.36)",
      appBarBackground: "rgba(7, 12, 24, 0.9)",
      backdropBackground: "rgba(2, 6, 23, 0.76)",
      tooltipBackground: "#0f172a",
      tooltipArrow: "#0f172a",
      textPrimary: "#e5eefc",
      textSecondary: "#9aa8bf",
    }),
  },
  {
    id: "light_clean",
    name: "Light Clean",
    theme: createPresetTheme({
      mode: "light",
      primary: "#2563eb",
      backgroundDefault: "#f4f7fb",
      surfaceBackground: "#ffffff",
      surfaceBorder: "rgba(15, 23, 42, 0.10)",
      surfaceShadow: "0 20px 50px rgba(15, 23, 42, 0.10)",
      paperShadow: "0 20px 50px rgba(15, 23, 42, 0.10)",
      appBarBackground: "rgba(255, 255, 255, 0.88)",
      backdropBackground: "rgba(15, 23, 42, 0.35)",
      tooltipBackground: "#111827",
      tooltipArrow: "#111827",
      textPrimary: "#0f172a",
      textSecondary: "#475569",
    }),
  },
  {
    id: "high_contrast",
    name: "High Contrast",
    theme: createPresetTheme({
      mode: "dark",
      primary: "#fbbf24",
      backgroundDefault: "#000000",
      surfaceBackground: "#0b0b0b",
      surfaceBorder: "rgba(255, 255, 255, 0.16)",
      surfaceShadow: "0 24px 70px rgba(0, 0, 0, 0.5)",
      paperShadow: "0 24px 70px rgba(0, 0, 0, 0.5)",
      appBarBackground: "rgba(0, 0, 0, 0.92)",
      backdropBackground: "rgba(0, 0, 0, 0.85)",
      tooltipBackground: "#0b0b0b",
      tooltipArrow: "#0b0b0b",
      textPrimary: "#ffffff",
      textSecondary: "#e5e7eb",
    }),
  },
  {
    id: "midnight_purple",
    name: "Midnight Purple",
    theme: createPresetTheme({
      mode: "dark",
      primary: "#a78bfa",
      backgroundDefault: "#080912",
      surfaceBackground: "rgba(18, 20, 35, 0.88)",
      surfaceBorder: "rgba(167, 139, 250, 0.16)",
      surfaceShadow: "0 24px 70px rgba(2, 6, 23, 0.38)",
      paperShadow: "0 24px 70px rgba(2, 6, 23, 0.38)",
      appBarBackground: "rgba(8, 10, 18, 0.86)",
      backdropBackground: "rgba(2, 6, 23, 0.74)",
      tooltipBackground: "#111827",
      tooltipArrow: "#111827",
      textPrimary: "#f3f4ff",
      textSecondary: "#b4b6d3",
    }),
  },
];

export function getThemeById(id) {
  return THEME_PRESETS.find((t) => t.id === id)?.theme || THEME_PRESETS[0].theme;
}
